#!/usr/bin/env sh

# Executa o Commitizen automaticamente ao rodar "git commit"
# (apenas se o usuário não usar -m "mensagem")
if [ -z "$2" ]; then
  exec < /dev/tty && npx cz --hook || true
  # Evita que o Git abra o editor padrão (commit-editmsg)
  exit 0
fi